Feature linked list Khodas Artyom
KhodasArtyom/TMS_C64_HomeWork13 pull request #2
Opened 2023-03-17 13:40 UTC by KhodasArtyom

2023-03-19 17:57 UTC, oleg-grigorijan requested changes

2023-03-19 17:57 UTC, oleg-grigorijan commented on src/by/TeachMeSkills/KhodasArtyom/homework13/listMethods/IntLinkedList.java
> +    public IntLinkedNode getHeadNote() {
Это деталь внутренней реализации класса. Мы не хотим, чтобы вызывающая сторона имела доступ к узлам в принципе. Такого public метода быть не должно

2023-03-19 17:57 UTC, oleg-grigorijan commented on src/by/TeachMeSkills/KhodasArtyom/homework13/listMethods/IntLinkedList.java
> +    private IntLinkedNode headNote;
Note -> Node

2023-03-19 17:57 UTC, oleg-grigorijan commented on src/by/TeachMeSkills/KhodasArtyom/homework13/listMethods/IntLinkedList.java
> +    private IntLinkedNode getLinkedNote(int index) {
Note -> Node

2023-03-19 17:57 UTC, oleg-grigorijan commented on src/by/TeachMeSkills/KhodasArtyom/homework13/listMethods/IntLinkedList.java
> +        return node;
Если мы выйдем из цикла по условию node != null (когда индекс за пределами правой границы списка), то в node будет null. То есть мы вернём отсюда null

2023-03-19 17:57 UTC, oleg-grigorijan commented on src/by/TeachMeSkills/KhodasArtyom/homework13/listMethods/IntLinkedListRealization.java
> +public class IntLinkedListRealization {
Как слово реализация на английском используют implementation. Но вообще реализация связного списка – это и есть LinkedList. Довольно путающий нейминг

2023-03-19 17:57 UTC, oleg-grigorijan commented on src/by/TeachMeSkills/KhodasArtyom/homework13/listMethods/HomeWork18.java
> +            }
А для связного списка? И как ты тестировал код?))

2023-03-20 07:08 UTC, KhodasArtyom commented on src/by/TeachMeSkills/KhodasArtyom/homework13/listMethods/HomeWork18.java
> +            }
Странно, я добавлял реализацию связанного списка в кейс 2 и тестировал. Вечером посмотрю

2023-03-22 14:21 UTC, oleg-grigorijan approved these changes

2023-03-22 14:21 UTC, oleg-grigorijan commented on src/by/TeachMeSkills/KhodasArtyom/homework13/listMethods/ImplementationArrayList.java
> +public class ImplementationArrayList {
Как и писал, путающее название с Implementation. Могу предложить использовать тут суффикс "Controller"

2023-03-22 14:21 UTC, oleg-grigorijan commented on src/by/TeachMeSkills/KhodasArtyom/homework13/listMethods/IntLinkedList.java
Автоформатирование

2023-03-22 16:36 UTC, merged